# Generated by Django 3.0.8 on 2020-08-04 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0008_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
