# Generated by Django 3.0.8 on 2020-08-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0009_remove_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
