# Generated by Django 3.0.8 on 2020-08-04 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0011_auto_20200804_0326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
